Aggiunta termini e definizioni al glossario
Archi7echs-Team/archi7echs-team.github.io pull request #71
Opened 2024-12-10 23:31 UTC by Blueerr

2024-12-18 14:43 UTC, Pyer23 requested changes
Mancano delle definizioni.

2025-01-03 07:28 UTC, francescopozzobon commented
richiesta nuova verifica @Pyer23 
cambiata approvazione finale. Autoassegnata.

2025-01-03 16:54 UTC, Pyer23 approved these changes

2025-01-03 17:29 UTC, francescopozzobon approved these changes

2025-01-03 17:37 UTC, merged